hydra:
  job:
    chdir: false
output_file: ???
rand_seed: 1
num_candidates: 1
num_ice: 1
dpp_sampling: false
dpp_topk: 100
scale_factor: null
rerank: false
batch_size: 64
cuda_device: cuda:0
overwrite: true
method: 'topk'
vote_k_k: 1
model_name: 'gpt2-xl'
retriever_model: 'all-mpnet-base-v2'
task_name: sst2
index_file: ???
emb_field: X
dataset_reader:
  task_name: sst2
  model_name: ${model_name}
  field: ${emb_field}
  dataset_split: validation
  dataset_path: null

index_reader:
  task_name: sst2
  model_name: ${model_name}
  field: ${emb_field}
  dataset_split: train
  dataset_path: null
model:
  _target_: transformers.AutoModelForCausalLM.from_pretrained
  pretrained_model_name_or_path: ${model_name}
